server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-demo
  cloud:
    config:
      label: master
      profile: local
      uri: http://localhost:8888/