server:
  port: 8762

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-demo
  cloud:
    config:
      label: master
      profile: local
      discovery:
        enabled: true
        service-id: config-server
    zookeeper:
      connect-string: 192.168.68.130:2181
      discovery:
        register: true