server:
  port: 8763

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-test
  cloud:
    zookeeper:
      connect-string: 192.168.68.130:2181

zuul:
  routes:
    service-demo:
      path: /service-demo/**
      serviceId: service-demo
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign